name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "packages/container/**"
defaults:
  run:
    working-directory: packages/container
jobs:
  buiid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}
      
    
